"""init

Revision ID: 451b1219d373
Revises: 
Create Date: 2026-01-15 19:53:38.171180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '451b1219d373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_key'), 'devices', ['device_key'], unique=True)
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_map_id'), 'maps', ['map_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('map_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'subject_type', 'subject_id', name='uq_map_access')
    )
    op.create_index(op.f('ix_map_access_map_id'), 'map_access', ['map_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('pose', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intrinsics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_map_id'), 'snapshots', ['map_id'], unique=False)
    op.create_table('telemetry_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('amr_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hist_map_amr_ts', 'telemetry_history', ['map_id', 'amr_id', 'ts'], unique=False)
    op.create_index(op.f('ix_telemetry_history_amr_id'), 'telemetry_history', ['amr_id'], unique=False)
    op.create_index(op.f('ix_telemetry_history_map_id'), 'telemetry_history', ['map_id'], unique=False)
    op.create_table('telemetry_last',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('amr_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_last_map_amr', 'telemetry_last', ['map_id', 'amr_id'], unique=True)
    op.create_index(op.f('ix_telemetry_last_amr_id'), 'telemetry_last', ['amr_id'], unique=False)
    op.create_index(op.f('ix_telemetry_last_map_id'), 'telemetry_last', ['map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_last_map_id'), table_name='telemetry_last')
    op.drop_index(op.f('ix_telemetry_last_amr_id'), table_name='telemetry_last')
    op.drop_index('ix_last_map_amr', table_name='telemetry_last')
    op.drop_table('telemetry_last')
    op.drop_index(op.f('ix_telemetry_history_map_id'), table_name='telemetry_history')
    op.drop_index(op.f('ix_telemetry_history_amr_id'), table_name='telemetry_history')
    op.drop_index('ix_hist_map_amr_ts', table_name='telemetry_history')
    op.drop_table('telemetry_history')
    op.drop_index(op.f('ix_snapshots_map_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_map_access_map_id'), table_name='map_access')
    op.drop_table('map_access')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_maps_map_id'), table_name='maps')
    op.drop_table('maps')
    op.drop_index(op.f('ix_devices_device_key'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
