"""update_3

Revision ID: de5cff3683bc
Revises: e9603f93fc55
Create Date: 2026-01-22 23:41:43.454586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5cff3683bc'
down_revision: Union[str, Sequence[str], None] = 'e9603f93fc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_key_hash', sa.String(length=255), nullable=False),
    sa.Column('device_key_digest', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_key_digest'), 'devices', ['device_key_digest'], unique=True)
    op.create_index(op.f('ix_devices_is_active'), 'devices', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_is_active'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_key_digest'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
