"""update 1

Revision ID: e0ba13db640d
Revises: 451b1219d373
Create Date: 2026-01-19 15:13:34.683795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ba13db640d'
down_revision: Union[str, Sequence[str], None] = '451b1219d373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_key_hash',
                  sa.String(length=255), nullable=False))
    op.add_column('devices', sa.Column('device_key_digest',
                  sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_devices_device_key'), table_name='devices')
    op.create_index(op.f('ix_devices_device_key_digest'),
                    'devices', ['device_key_digest'], unique=True)
    op.drop_column('devices', 'device_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_key', sa.VARCHAR(
        length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_devices_device_key_digest'), table_name='devices')
    op.create_index(op.f('ix_devices_device_key'),
                    'devices', ['device_key'], unique=True)
    op.drop_column('devices', 'device_key_digest')
    op.drop_column('devices', 'device_key_hash')
    # ### end Alembic commands ###
