"""update 2

Revision ID: e9603f93fc55
Revises: e0ba13db640d
Create Date: 2026-01-19 15:23:56.372852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9603f93fc55'
down_revision: Union[str, Sequence[str], None] = 'e0ba13db640d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_key_hash', sa.String(length=255), nullable=False),
    sa.Column('device_key_digest', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_key_digest'), 'devices', ['device_key_digest'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_device_key_digest'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
